// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvpifqpfxscjfudhvuyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2cGlmcXBmeHNjamZ1ZGh2dXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzgyOTQsImV4cCI6MjA2NDU1NDI5NH0.Jxl01VTyDVkyNEp-4ayX7ON74mbGKHLu-Urj_U93Pxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);